{% set name = "robotframework-databaselibrary" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ed5db7a48bd2fcb2572e435e09d5ebb97b715026e792f7dcf49af29c951fd7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - robotframework >=5.0.1
    - robotframework-assertion-engine
    - pip
  run:
    - python >={{ python_min }}
    - robotframework >=5.0.1
    - robotframework-excellib
    - robotframework-assertion-engine

test:
  imports:
    - DatabaseLibrary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/franz-see/Robotframework-Database-Library
  summary: Database utility library for Robot Framework
  doc_url: https://pythonhosted.org/robotframework-databaselibrary/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
