{% set name = "robotframework-databaselibrary" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a1a81dccf477627ebff5efc399f6a2cc3b1092ad40a0b7074afa0102a39a7cf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - robotframework >=5.0.1
    - robotframework-assertion-engine
    - sqlparse
    - pip
  run:
    - python >={{ python_min }}
    - robotframework >=5.0.1
    - robotframework-excellib
    - robotframework-assertion-engine
    - sqlparse

test:
  imports:
    - DatabaseLibrary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/franz-see/Robotframework-Database-Library
  summary: Database utility library for Robot Framework
  doc_url: https://pythonhosted.org/robotframework-databaselibrary/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
