{% set name = "robotframework-databaselibrary" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework-databaselibrary-{{ version }}.tar.gz
  sha256: 4e9cd4c96937420ed3bb5baee65c4320bbd7ecc73a0836895c2c1dd9c2a99acf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - robotframework
    - pip
  run:
    - python >=3.7
    - robotframework
    - robotframework-excellib

test:
  imports:
    - DatabaseLibrary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/franz-see/Robotframework-Database-Library
  summary: Database utility library for Robot Framework
  doc_url: https://pythonhosted.org/robotframework-databaselibrary/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
